### ISSUE TITLE
Error when trying your generator example

### ISSUE THREAD

**Issue by dmstern** [boneskull/create-yo#8] opened 2019-10-17 09:31 UTC
This is a very cool idea! 

I tried it with the example from your blog post:

```bash
npm init yo generator
```

This was the output:

```bash
$ npm init yo generator
npx: Installierte 15 in 2.075s
Command failed: C:\"Program Files"\nodejs\node.exe "C:\Users\dmorgenstern\AppData\Roaming\npm\npm" config get cache --parseable
C:\Users\dmorgenstern\AppData\Roaming\npm\npm:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

√ create-yo ok!
```

**My System:**
* Windows 10
* Cmder
```bash
$ node -v  
v8.15.0    
```
```bash
$ npm -v
6.4.1
```

Am I doing something wrong?

**Comment by eamodio** [comment] 2019-10-30 14:46
I see the same thing on Windows 10. But with node `v10.16.0`

**Comment by boneskull** [comment] 2020-05-12 23:50
duplicate of #4

**Closed by boneskull** 2020-05-12 23:50 UTC
